// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoMFE.Models
{
    public partial class Dispositivos
    {
        public Dispositivos()
        {
            Solicitudes = new HashSet<Solicitudes>();
        }

        public string NumSerie { get; set; }
        public int IdCategoria { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Localizacion { get; set; }
        public string Estado { get; set; }

        public virtual Categorias IdCategoriaNavigation { get; set; }
        public virtual HwRed HwRed { get; set; }
        public virtual Ordenadores Ordenadores { get; set; }
        public virtual Pantallas Pantallas { get; set; }
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
    }
}