// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoMFE.Models
{
    public partial class HistoricoSolicitudes
    {
        public string NumSerie { get; set; }
        public int IdUsuario { get; set; }
        public DateTime Fecha { get; set; }
        public string Ultimatum { get; set; }
    }
}