// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoMFE.Models
{
    public partial class HwRed
    {
        public string NumSerie { get; set; }
        public int NumPuertos { get; set; }
        public int Velocidad { get; set; }

        public virtual Dispositivos NumSerieNavigation { get; set; }
    }
}