// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProyectoMFE.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ProyectoMFE.Models
{
    public partial interface IProyectoMFEContextProcedures
    {
        Task<int> ACEPTAR_SOLICITUDAsync(string correo, string num_dispositivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> FINALIZAR_SOLICITUDAsync(string correo, string num_dispositivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> INSERTAR_SOLICITUDAsync(string correo, string num_dispositivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> RECHAZAR_SOLICITUDAsync(string correo, string num_dispositivo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
