// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProyecto.Models
{
    public partial class Ordenadores
    {
        public string NumSerie { get; set; }
        public string Procesador { get; set; }
        public string Ram { get; set; }
        public string DiscoPrincipal { get; set; }
        public string DiscoSecundario { get; set; }

        public virtual Dispositivos NumSerieNavigation { get; set; }
    }
}