// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProyecto.Models
{
    public partial class Pantallas
    {
        public string NumSerie { get; set; }
        public int Pulgadas { get; set; }

        public virtual Dispositivos NumSerieNavigation { get; set; }
    }
}